create_df: False
include_dif: False
use_only_dif: False
channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
output_folder: '/share_alpha_2/amandalucas/cluster_analysis/exp1/'
n_factors: 3 # empty to perform EFA