# PRE-PROCESSING PARAMETERS
# debug_mode - save pairs as both npy and jpeg
debug_mode: True
# change_detection - if True, uses T1 + T2. if False, use only T2.
change_detection: True 
# two_classes_problem - if True, uses a binary mask. if False, uses a 3-classes mask.
two_classes_problem: False 
# tiles usados para treinamento e validacao
tiles_tr: [1,3,5,7,8,10,11,13,14,16,18,20,4,6,19]
tiles_val: [2, 9, 12]
# stride is set to 0.5*patch_size
patch_size: 256
overlap: 0.5
save_patches: False # if False, save only image pairs (expected input from pix2pix net)
save_tiles: True # save testing tiles 
create_input_pix2pix: False # if True, save rejected image pairs in order to feed them to the trained generator
synthetic_input_mode: 0 # 0: usa as mascaras originais, 1: usa mascaras dilatadas...
# minimum NEW deforestation required per patch (new deforestation - class 1)
# 0: forest, 1: new deforestation, 2: old deforestation
min_percentage: 5
# path to images
root_path: '../Sentinel2/' 
# path to save patches
output_path: '/share_alpha_2/amandalucas/pix2pix/Sentinel2/samples'
# limite utilizado das imagens de entrada -> image is (17729, 9202)
lim_x: 17700 # 1000
lim_y: 9200 # 7000
# tipo de normalizacao utilizada. ps.: o codigo do pix2pix ja faz a normalizacao entre [0,1]
# 0: MinMax(0,255), 1: Standard, 2: MinMax(0,1), 3: MinMax(-1,1)
type_norm: 0
# quais bandas serao utilizadas
channels: [0, 1, 3] 
# 0 - blue *
# 1 - green *
# 2 - red
# 3 - NIR *
# 4 - vegetation red edge (0.705 um)
# 5 - vegetation red edge (0.740 um)
# 6 - vegetation red edge (0.783 um)
# 7 - vegetation red edge (0.865 um)
# 8 - SWIR (1.610 um)
# 9 - SWIR (2.190um)
extract_minipatches: False
minipatch_size: 32

# TRAINING PARAMETERS - PIX2PIX
training_name: 'change_detection_true_two_classes_true'
data_path: '/share_alpha_2/amandalucas/pix2pix/Sentinel2/samples_change_detection_true_two_classes_false'
training_steps: 250000
checkpoint_steps: 10000 # interval to save checkpoint
batch_size: 1 # The batch size of 1 produced better results for the U-Net in the original pix2pix experiment
lambda: 100
image_width: 256
image_height: 256
output_channels: 3
# buffer_size: 100

# TRAINING PARAMETERS - UNET
input_channels: 3
epochs_unet: 100
batch_size_unet: 32
nb_filters: [32, 64, 128]
times: 1
patience_value: 10