only_bgr_channels: True
two_classes_problem: True # usa a mascara como mascara binaria com 2 classes (desmatamento e nao desmatamento)
tiles_tr: [1,3,5,7,8,10,11,13,14,16,18,20,4,6,19]
tiles_val: [2, 9, 12]
patch_size: 256 # stride is set to 0.5*patch_size
min_percentage: 7 # minimum deforestation required per patch
root_path: '../Sentinel2/' # path to images
output_path: '/share_alpha_2/amandalucas/pix2pix/Sentinel2/samples_new_split' # path to save patches
lim_x: 17000 # 1000
lim_y: 9200 # 7000
channels: [0, 1, 3] # quais canais usar da imagem
# 0 - blue [10m]
# 1 - green [10m]
# 2 - red [10m]
# 3 - NIR [10m]
# 4 - vegetation red edge (0.705 um) [20m]
# 5 - vegetation red edge (0.740 um) [20m]
# 6 - vegetation red edge (0.783 um) [20m]
# 7 - vegetation red edge (0.865 um) [20m]
# 8 - SWIR (1.610 um) [20m]
# 9 - SWIR (2.190um) [20m]
minipatch_size: 32
