debug_mode: True
# usa a mascara como mascara binaria com 2 classes (desmatamento e nao desmatamento)
# e considera apenas a imagem T2
two_classes_problem: True
# tiles usados para treinamento e validacao
tiles_tr: [1,3,5,7,8,10,11,13,14,16,18,20,4,6,19]
tiles_val: [2, 9, 12]
# stride is set to 0.5*patch_size
patch_size: 256
save_patches: False # if False, save only image pairs (expected input from pix2pix net)
# minimum deforestation required per patch (class 1)
min_percentage: 7 
# path to images
root_path: '../Sentinel2/' 
# path to save patches
output_path: '/share_alpha_2/amandalucas/pix2pix/Sentinel2/samples'
# limite utilizado das imagens de entrada
lim_x: 17000 # 1000
lim_y: 9200 # 7000
# tipo de normalizacao utilizada. ps.: o codigo do pix2pix ja faz a normalizacao entre [0,1]
# 0: MinMax(0,255), 1: Standard, 2: MinMax(0,1), 3: MinMax(-1,1)
type_norm: 0
# quais bandas serao utilizadas
channels: [0, 1, 3] 
# 0 - blue *
# 1 - green *
# 2 - red
# 3 - NIR *
# 4 - vegetation red edge (0.705 um)
# 5 - vegetation red edge (0.740 um)
# 6 - vegetation red edge (0.783 um)
# 7 - vegetation red edge (0.865 um)
# 8 - SWIR (1.610 um)
# 9 - SWIR (2.190um)

extract_minipatches: False
minipatch_size: 32
