only_bgr_channels: True
two_classes_problem: True # usa a mascara como mascara binaria com 2 classes (desmatamento e nao desmatamento)
tiles_tr: [1,3,5,7,8,10,11,13,14,16,18,20,4,6,19]
tiles_val: [2, 9, 12]
patch_size: 256 # stride is set to 0.5*patch_size
min_percentage: 5 # minimum deforestation required per patch
root_path: '../Sentinel2/'
output_path: '/share_epsilon/amandalucas/pix2pix/Sentinel2/samples_new_split' 
lim_x: 17000 # 1000
lim_y: 9200 # 7000
channels: [1, 2, 3] # quais canais usar da imagem
# 0 - blue
# 1 - green
# 2 - red
# 3 - NIR
# 4 - vegetation red edge (0.705 um)
# 5 - vegetation red edge (0.740 um)
# 6 - vegetation red edge (0.783 um)
# 7 - vegetation red edge (0.865 um)
# 8 - SWIR (1.610 um)
# 9 - SWIR (2.190um)

minipatch_size: 32